### PR TITLE
chore(repo): don't recommend deprecated vscode extension

### PR DESCRIPTION
**Pull request by lorenzleutgeb**
This extension greets me with

> The "TypeScript Vue Plugin (Volar)" extension is no longer needed since v2. Please uninstall it.

everytime I start VSCode. It's deprecated, so why not remove it?

### CODE REVIEW

**Comment by maninak** [comment]
Nice catch! Yes, volar got a massive upgrade recently (after they patched VS Code, TypeScript and TS's language server) and can finally deprecate that plugin which was a polished hack.

**Review by maninak — APPROVED** [review]
Thank you! <3

------

Normally we should also upgrade the lockfile to not fetch the removed dep, but I already have a massive [wip] branch with dep updates so best that it happens over there only.

**Comment by lorenzleutgeb** [comment]
> Normally we should also upgrade the lockfile to not fetch the removed dep, but I already have a massive [wip] branch with dep updates so best that it happens over there only.

Interesting. I didn't know that there's a lockfile for VSCode extensions and grep only finds this single occurrence:

```
$ rg --hidden --no-ignore 'vscode-typescript-vue-plugin'
.vscode/extensions.json
9:    "Vue.vscode-typescript-vue-plugin",
```

I'm just curious to understand this better, since I am new to VSCode extension development. Which lockfile do you mean?

**Comment by maninak** [comment]
> Which lockfile do you mean?

Oh, I'm referring to `pnpm-lock.yaml`. The extension is a standard node app in that regard. But for this kind of questions, it's best to take it on zulip to keep the history here clean.

**Comment by maninak** [comment]
Merged! Thanks for helping keep things tidy. :)

**Pull request merged**
